export const productData = [
    {
        id: 1,
        title: 'Processador Intel Core i9-13900K, 24-Core, 32-Threads, 3.0GHz (5.8GHz Turbo)',
        price: 3899.99,
        rating: 4.9,
        tag: 'Novo',
        imageUrl: '/images/cpu.png',
    },
    {
        id: 2,
        title: 'Placa de Vídeo NVIDIA GeForce RTX 4080, 16GB GDDR6X, DLSS 3, Ray Tracing',
        price: 8499.5,
        rating: 4.8,
        tag: 'Promo',
        imageUrl: '/images/gpu.png',
    },
    {
        id: 3,
        title: 'Memória RAM Corsair Vengeance RGB Pro, 32GB (2x16GB), DDR5, 6000MHz',
        price: 950.0,
        rating: 4.7,
        tag: null,
        imageUrl: '/images/ram.png',
    },
    {
        id: 4,
        title: 'SSD Kingston NV2, 2TB, M.2 2280, NVMe, Leitura 3500MB/s, Gravação 2800MB/s',
        price: 749.99,
        rating: 4.6,
        tag: 'Novo',
        imageUrl: '/images/ssd.png',
    },
    {
        id: 5,
        title: 'Placa-Mãe Gigabyte Z790 AORUS ELITE, Intel LGA 1700, ATX, DDR5, Wi-Fi',
        price: 2199.0,
        rating: 4.8,
        tag: 'Promo',
        imageUrl: '/images/motherboard.png',
    },
    {
        id: 6,
        title: 'Monitor Gamer Alienware 27", QHD, 280Hz, 1ms, IPS, G-Sync, AW2723DF',
        price: 4320.0,
        rating: 4.9,
        tag: null,
        imageUrl: '/images/monitor.png',
    },
]
